/* Downloads the exact woff2 files the site uses from Google Fonts and writes a
   self-hosted assets/fonts/fonts.css. Run once (or when weights change):
     node scripts/fetch-fonts.mjs
   Self-hosting removes the external font CDN (perf) and avoids leaking visitor
   IPs to Google (GDPR). Committed woff2 files mean production needs no refetch. */
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const outDir = path.join(root, 'assets', 'fonts');

const CSS_URL =
  'https://fonts.googleapis.com/css2' +
  '?family=Archivo:wght@600;700;800' +
  '&family=IBM+Plex+Mono:wght@400;500' +
  '&family=IBM+Plex+Sans:wght@400;500;600' +
  '&family=Newsreader:ital,opsz,wght@0,6..72,400;0,6..72,500;0,6..72,600;1,6..72,400;1,6..72,500' +
  '&display=swap';

// A modern desktop UA makes Google serve woff2 (older UAs get ttf).
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/124.0 Safari/537.36';

// Keep only Latin subsets — the site's copy is English.
const KEEP = new Set(['latin', 'latin-ext']);

function slug(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

const css = await fetch(CSS_URL, { headers: { 'User-Agent': UA } }).then((r) => {
  if (!r.ok) throw new Error('Google Fonts CSS fetch failed: ' + r.status);
  return r.text();
});

await mkdir(outDir, { recursive: true });

// Split into "/* subset */ @font-face { ... }" units.
const units = css.split('@font-face').slice(1);
let out = '/* Self-hosted fonts — generated by scripts/fetch-fonts.mjs. Do not edit by hand. */\n\n';
let count = 0;

for (let i = 0; i < units.length; i++) {
  const before = i === 0 ? css.split('@font-face')[0] : units[i - 1];
  const subsetMatch = before.match(/\/\*\s*([a-z0-9-]+)\s*\*\/\s*$/i);
  const subset = subsetMatch ? subsetMatch[1] : 'latin';
  if (!KEEP.has(subset)) continue;

  const block = units[i];
  const family = (block.match(/font-family:\s*'([^']+)'/) || [])[1] || 'font';
  const weight = (block.match(/font-weight:\s*(\d+)/) || [])[1] || '400';
  const style = (block.match(/font-style:\s*(\w+)/) || [])[1] || 'normal';
  const srcUrl = (block.match(/src:\s*url\(([^)]+)\)/) || [])[1];
  if (!srcUrl) continue;

  const name = `${slug(family)}-${weight}-${style}-${subset}.woff2`;
  const buf = Buffer.from(await fetch(srcUrl, { headers: { 'User-Agent': UA } }).then((r) => r.arrayBuffer()));
  await writeFile(path.join(outDir, name), buf);

  const unicodeRange = (block.match(/unicode-range:\s*([^;]+);/) || [])[1];
  out += `@font-face {\n`;
  out += `  font-family: '${family}';\n`;
  out += `  font-style: ${style};\n`;
  out += `  font-weight: ${weight};\n`;
  out += `  font-display: swap;\n`;
  out += `  src: url('/assets/fonts/${name}') format('woff2');\n`;
  if (unicodeRange) out += `  unicode-range: ${unicodeRange.trim()};\n`;
  out += `}\n\n`;
  count++;
}

await writeFile(path.join(outDir, 'fonts.css'), out);
console.log(`Wrote ${count} font files + fonts.css to assets/fonts/`);
